version: '2.1'

services:

  matrix:
    container_name: matrix
    build: .
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig # Configures APP to be DEV aware